Repository privacy-scaling-explorations/zk-kit.rust, pull requests merged in 2024-08, with the labels that each got.

#41 feat(smt): add `smt` crate
  Cargo.lock
  crates/smt/Cargo.toml
  crates/smt/LICENSE
  crates/smt/README.md
  crates/smt/examples/smt.rs
  crates/smt/src/lib.rs
  crates/smt/src/smt.rs
  crates/smt/src/utils.rs
Labels: feature :rocket:

#46 chore: generate coverage report
  .github/workflows/main.yml
  .setup.sh
  Makefile
Labels: devops :wrench:, tests 🧪

#47 ci: checkout before reporting coverage to coveralls
  .github/workflows/main.yml
Labels: bug 🐛, devops :wrench:

#49 docs: add coverage badge
  README.md
Labels: documentation 📖
